### ISSUE TITLE
Login - Back button on Otp page shows login page without number in the input

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#115]
**Describe the Issue**
The back button on Otp page shows login page without number in the input

**Steps**
1. Enter the number on the login page and click on continue
2. On the OTP screen click on the back button

**Expected Result**
The Login page with the number as input should be shown

**Actual result**
The Login page with a blank Input field is shown.

**Comment by Melwyn-Carvalho** [comment]
@hipolucas @sujitgawas19 
Issue still exists

**Comment by sujitgawas19** [comment]
This issue was fixed.. hippo removed my code while merging

**Comment by larissa-c-d** [comment]
Issue resolved
