### ISSUE TITLE
"Verify OTP" button should not be there as per the requirement document

### ISSUE THREAD

**Issue by finaegistech** [ajency/Finaegis-Backend#15]
Screen for "OTP" is not in sync with UI design and requirement document.
OTP should be auto verified (without click on any button) as per the requirement document.

Expected Result -
OTP should be auto verified once provided all 6 digits

Actual Result - 
Needs to click on "Verify OTP" button.

**Comment by sharangsamonkar** [comment]
@georgioajency What did we decide for this?

**Comment by georgioajency** [comment]
We auto detect the OTP and submit

User can also enter the values. A verify OTP call is done when all 6 digits are entered.

Button to verify OTP will be not be there.
