### ISSUE TITLE
OTP - Invalid Otp message gets reset 

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#157]
**Describe the Issue**
Invalid Otp message gets reset 

**Steps**
1. Click on Login
2. On OTP page, enter invalid otp 3 times. A message will be displayed saying 'you have 27 tries'
3. Click on back button
4. Click on continue
5. Enter an invalid otp again. Message will be shown saying 'you have 29 tries left'

**Expected result**
The message saying 'you have 26 tries left ' should be shown

**Comment by verlekar-viraj** [comment]
Once you go back & continue again, it is a new OTP sent. The tries for that OTP is 0. @georgioajency should the tries for the new OTP continue?

**Comment by georgioajency** [comment]
Ideally, it should continue. But keep it as it is for now.

Remove the text. 27 tries remaining
