### ISSUE TITLE
Investment Account-Issues

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#255]
- [x] The text finaegis is not displayed

- [x] user name is not displayed for non client number

- [ ] The phone number is not displayed  for non client number **--Issue still exists**

- [x] Text "Complete your Account Set-Up and start Investing" should be changed to "Complete your account set-up and start Investing"

- [x] Font weight for card headings should be increased. **--Font weight should be Medium**

- [x] Font size for the text on the cards should be increased. **--Font size not increased to match the design** 

- [x] Your Advisors card is not highlighted

- [x] Text for bank details should be changed to " Manage your Bank Accounts and Mandates"

- [x] Text  displayed under My family members should be changed to View/Add Members

- [x] The Font weight for the user name should be increased **--Still exists**

- [x] The  font size of the phone number should be increased

- [x] The colour of the icons on the cards does not match the design.

- [x] Text displayed under support should be changed

- [ ] The text profile and Portfolio are underlined on iPhone
![image](https://user-images.githubusercontent.com/54023516/85117321-53af4a00-b23c-11ea-8d69-d55276b88a9f.png)

**Comment by larissa-c-d** [comment]
- [ ] The Font size for the text "Hi there!" should be increased

**Comment by georgioajency** [comment]
Text for bank details should be changed to " Manage your Bank Accounts and Mandates"
This is fine
