### ISSUE TITLE
My Family Members - Empty state screen (Hide the card if it is empty) (G)

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#279]

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/84885982-6a756580-b0b1-11ea-9478-9970672d8390.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/84988259-538d4c80-b15f-11ea-8d02-6d9fccc95acb.png)
