### ISSUE TITLE
 Database - Father's name and mother's name added on Zoho is not displayed in the client_personal_details table

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#29]
**Steps**
1. Under the Family Details section, enter data and submit
2. View data present in the database for the table client_personal_details

**Screenshots**
![image](https://user-images.githubusercontent.com/52652632/82897691-9f404200-9f75-11ea-845c-c8e7dd2f6ba5.png)

![image](https://user-images.githubusercontent.com/52652632/82897819-d9114880-9f75-11ea-9bdf-f2de9130e9df.png)

**Comment by sharangsamonkar** [comment]
This is nominee relationship. Need to discuss on this.

@georgioajency We are having a separate field for mothers name and fathers name right?

**Comment by georgioajency** [comment]
Yes, both are separate. 

Not necessarily nominee. It is a required field when creating an investment account.
