### ISSUE TITLE
Personal Information-The text "Looks like your profile is incomplete. Contact our support team to complete your profile now." is not displayed when the personal details are not completed

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#323]
Actual result
Personal Information-The text "Looks like your profile is incomplete. Contact our support team to complete your profile now." is not displayed when the personal details are not completed

**Screenshot**
![image](https://user-images.githubusercontent.com/54023516/84860528-d0032b00-b08c-11ea-9f4a-77a0aa05cf64.png)

Expected result
Personal Information-The text "Looks like your profile is incomplete. Contact our support team to complete your profile now."  should be displayed when the personal details are not completed

**Comment by georgioajency** [comment]
New update. Just came in today.

**Comment by georgioajency** [comment]
Not doing this
