### ISSUE TITLE
"Continue" button is seen instead of "Send OTP" button

### ISSUE THREAD

**Issue by finaegistech** [ajency/Finaegis-Backend#33]
Steps -
1. Click on "Get Started"
2. Navigate to Sign in / Sign up page

Expected Result -
As per the UI design it should be "Send OTP". It was "Send OTP" in previous build (0.0.3)

Actual Result -
"Continue" button is displayed.
![26thMay_3](https://user-images.githubusercontent.com/65398292/82926174-6ebfce80-9f9c-11ea-89bf-2fb7538d451b.jpg)

**Comment by georgioajency** [comment]
Updated this text because of the agreement policy text at the bottom
