### ISSUE TITLE
The selected tab should be highlighted in green 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#356]
Actual result
The selected tab should be highlighted in green 

Screenshot
![image](https://user-images.githubusercontent.com/54023516/85000795-82f88500-b170-11ea-868f-bfa0e57182cf.png)

**Comment by georgioajency** [comment]
It's highlighted in green nah?

**Comment by larissa-c-d** [comment]
was an issue, resolved
