### ISSUE TITLE
The portfolio and profile tab should have a solid backgound

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#357]
Actual result
The portfolio and profile tab  background have an opacity.

Screenshot
![image](https://user-images.githubusercontent.com/54023516/85001811-c273a100-b171-11ea-8b2f-6a459be80071.png)

**Comment by georgioajency** [comment]
Issue

**Comment by larissa-c-d** [comment]
Issue  resolved
