### ISSUE TITLE
Portfolio and Profile tabs  are not present 

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#360]
Actual result
Tabs are not present on Support and More for Android and are not present on personal information,Bank details,My family members,support,More for iPhone.

Screenshot
![image](https://user-images.githubusercontent.com/54023516/85003850-66f6e280-b174-11ea-9609-f50be4844fc5.png)

![image](https://user-images.githubusercontent.com/54023516/85003841-63635b80-b174-11ea-91cd-4f9b5a9d48b6.png)

![image](https://user-images.githubusercontent.com/54023516/85117057-e0a5d380-b23b-11ea-801b-a9652e1ab126.png)

**Comment by georgioajency** [comment]
You mean the navigation tab?

**Comment by larissa-c-d** [comment]
The bottom portfolio and profile tabs
![image](https://user-images.githubusercontent.com/54023516/85116693-53627f00-b23b-11ea-9182-5cb25beeb94c.png)

**Comment by georgioajency** [comment]
Not a issue, tabs should not appear inside.
