### ISSUE TITLE
The name displayed should be consistent through out

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#371]
Actual result
The Name on My Family page
![image](https://user-images.githubusercontent.com/54023516/85105095-797e2400-b227-11ea-97fa-6703c7f00c29.png)

The Name on Profile
![image](https://user-images.githubusercontent.com/54023516/85105084-75520680-b227-11ea-9a47-7ffc4c2852fd.png)

The name on Personal Information page
![image](https://user-images.githubusercontent.com/54023516/85105102-7e42d800-b227-11ea-8802-fa8801565eed.png)

**Comment by georgioajency** [comment]
Not an issue
