### ISSUE TITLE
My Family members section is not displayed for a non client number

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/Finaegis-Backend#373]
Actual result
My Family members section is not displayed for a non client number

Screenshot
![image](https://user-images.githubusercontent.com/54023516/85107293-5f464500-b22b-11ea-80b1-94a3055bae8f.png)

Steps
1.Go to the profile page

**Comment by georgioajency** [comment]
This is correct. They will not have a family so the tab will not be shown
