### ISSUE TITLE
Carousel - Carousel dots missing and design mismatch

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#39]
**Describe the Issue**
Carousel dots missing and design mismatch (all 3 screens)

**Screenshots**
![image](https://user-images.githubusercontent.com/52652632/82981628-1e7f5580-a00a-11ea-926c-78f9f498fd14.png)

Reference:
![image](https://user-images.githubusercontent.com/52652632/82981648-2939ea80-a00a-11ea-826e-aac587521013.png)

**Comment by georgioajency** [comment]
Low Priority. Update later
