### ISSUE TITLE
Login Screen - Can Navigate to Carousel screen by clicking on back button of phone

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#40]
**Describe the Issue**
Can Navigate to Carousel screen by clicking on back button of phone

**Steps**
1. Click on Get Started button
2. On the login screen click on back button of the phone

**Expected Result**
Back button should not navigate to the carousel screen and should provide a prompt to exit the app

**Comment by georgioajency** [comment]
Should close the app after I am done with the app intro. 

High priority
