### ISSUE TITLE
Login - Text missing ' The Cambridge Wealth app is secure'

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#41]
**Describe the Issue**
Text missing ' The Cambridge Wealth app is secure'

**Screenshots**
![image](https://user-images.githubusercontent.com/52652632/82982410-c5182600-a00b-11ea-9064-aabe19727cf6.png)

Reference:
![image](https://user-images.githubusercontent.com/52652632/82982441-d5c89c00-a00b-11ea-891f-0c3aabc6e6ec.png)

**Comment by georgioajency** [comment]
Low priority. There might be some additional screen work here. Next sprint

**Comment by georgioajency** [comment]
Low priority. There might be some additional screen work here. Next sprint
