### ISSUE TITLE
Resend button should display "Max 3 times " message after 3 times

### ISSUE THREAD

**Issue by finaegistech** [ajency/Finaegis-Backend#43]
Steps -
1. Enter valid phone number.
2. Go to "OTP" Screen.
3. Click on Resend button (3 continuous attempts)

Expected Result -
1. Should notify user that the OTP is being send to the number and to wait till otp is received.
2. Should auto- read otp once received
3. After 3rd attempt, it should display message - "Max 3 attempts allowed in 1 hour" 
4. Resend should be disabled.

Actual Result -
1. No notification to user to wait for the otp. User can keep clicking on Resend if not received otp in few seconds.
2. otp not auto read from message box
3. After 3rd attempt, no message of "max attempts" and Resend can be clicked many times. It does not send any otp after 3rd attempt but message is not displayed.

**Comment by georgioajency** [comment]
Text message already provided to Viraj. Please fix

**Comment by Melwyn-Carvalho** [comment]
Resend button should be disabled after the third time
