### ISSUE TITLE
OTP - If back button is clicked on the OTP screen, the button on the Login screen remains disabled even if there is a valid number present

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#44]
**Describe the Issue**
If back button is clicked on the OTP screen, the button on the Login screen remains disabled even if there is a valid number present

**Screenshots**
![image](https://user-images.githubusercontent.com/52652632/82983002-fc3b0700-a00c-11ea-80c8-0fba335ef583.png)

**Steps**
1. On Otp screen click on back button
2. The button on the Login screen will be disabled 

**Expected Result**
The button should be enabled

**Comment by georgioajency** [comment]
Issue. High priority
