### ISSUE TITLE
OTP - On entering an invalid OTP, the input entered does not get cleared

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#48]
**Describe the Issue**
On entering an invalid OTP, the input entered does not get cleared

**Screenshots**
![image](https://user-images.githubusercontent.com/52652632/82984033-e9c1cd00-a00e-11ea-9e83-af65317dd68d.png)

**Expected Result**
The input entered should be cleared

**Comment by georgioajency** [comment]
Med Priority
