### ISSUE TITLE
Login - Text of button should be 'Send OTP' instead of 'Continue'

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#52]
**Describe the Issue**
Text of button should be 'Send OTP' instead of 'Continue'

**Screenshots**
![pic 2](https://user-images.githubusercontent.com/52652632/82988673-28f41c00-a017-11ea-8d3a-cf8d1fe8d389.PNG)

**Comment by georgioajency** [comment]
Ignore
