### ISSUE TITLE
Home - If back button is clicked on Home page, Login page is displayed

### ISSUE THREAD

**Issue by Melwyn-Carvalho** [ajency/Finaegis-Backend#55]
**Describe the Issue**
If the back button is clicked on the Home page, the Login page is displayed

**Expected Result**
If the back button is clicked, a popup should be shown with an option to close/end the session

**Comment by georgioajency** [comment]
Should either take the user to the previous screen that they came from aka landing page. 

Or empty browser tab.

User cannot be taken back to the login page.
